"""Tests for CuraEngine printer definitions and BAMBOX header parsing."""

from __future__ import annotations

import json

from bambox.cura import (
    available_cura_printers,
    cura_definitions_dir,
    parse_bambox_headers,
)


class TestCuraDefinitions:
    def test_definitions_dir_exists(self) -> None:
        d = cura_definitions_dir()
        assert d.exists()
        assert d.is_dir()

    def test_available_printers(self) -> None:
        printers = available_cura_printers()
        assert "bambox_p1s_ams" in printers

    def test_p1s_ams_definition_valid_json(self) -> None:
        defn = cura_definitions_dir() / "bambox_p1s_ams.def.json"
        data = json.loads(defn.read_text())
        assert data["version"] == 2
        assert data["inherits"] == "fdmprinter"
        assert data["overrides"]["machine_extruder_count"]["value"] == 4

    def test_p1s_ams_has_bambox_headers_in_start_gcode(self) -> None:
        defn = cura_definitions_dir() / "bambox_p1s_ams.def.json"
        data = json.loads(defn.read_text())
        start = data["overrides"]["machine_start_gcode"]["default_value"]
        assert "; BAMBOX_PRINTER=p1s" in start
        assert "; BAMBOX_ASSEMBLE=true" in start

    def test_p1s_ams_has_4_extruder_trains(self) -> None:
        defn = cura_definitions_dir() / "bambox_p1s_ams.def.json"
        data = json.loads(defn.read_text())
        trains = data["metadata"]["machine_extruder_trains"]
        assert len(trains) == 4
        for i in range(4):
            assert str(i) in trains

    def test_extruder_definitions_exist(self) -> None:
        d = cura_definitions_dir()
        for i in range(4):
            ext = d / f"bambox_p1s_ams_extruder_{i}.def.json"
            assert ext.exists(), f"Missing extruder definition: {ext.name}"

    def test_extruders_share_nozzle(self) -> None:
        """AMS extruders share a single nozzle (zero offset)."""
        d = cura_definitions_dir()
        for i in range(4):
            ext = json.loads((d / f"bambox_p1s_ams_extruder_{i}.def.json").read_text())
            overrides = ext["overrides"]
            assert overrides["machine_nozzle_offset_x"]["default_value"] == 0
            assert overrides["machine_nozzle_offset_y"]["default_value"] == 0

    def test_extruders_emit_filament_headers(self) -> None:
        """Each extruder emits BAMBOX_FILAMENT_SLOT and BAMBOX_FILAMENT_TYPE."""
        d = cura_definitions_dir()
        for i in range(4):
            ext = json.loads((d / f"bambox_p1s_ams_extruder_{i}.def.json").read_text())
            start = ext["overrides"]["machine_extruder_start_code"]["default_value"]
            assert f"; BAMBOX_FILAMENT_SLOT={i}" in start
            assert "; BAMBOX_FILAMENT_TYPE=" in start


class TestParseBamboxHeaders:
    def test_basic_headers(self) -> None:
        gcode = (
            "; BAMBOX_PRINTER=p1s\n"
            "; BAMBOX_BED_TEMP=60\n"
            "; BAMBOX_ASSEMBLE=true\n"
            "; BAMBOX_END\n"
            "G28\n"
        )
        h = parse_bambox_headers(gcode)
        assert h["PRINTER"] == "p1s"
        assert h["BED_TEMP"] == "60"
        assert h["ASSEMBLE"] == "true"

    def test_stops_at_bambox_end(self) -> None:
        gcode = "; BAMBOX_PRINTER=p1s\n; BAMBOX_END\n; BAMBOX_IGNORED=yes\n"
        h = parse_bambox_headers(gcode)
        assert "IGNORED" not in h

    def test_multi_value_keys(self) -> None:
        """Multiple BAMBOX_FILAMENT_TYPE lines become comma-separated."""
        gcode = "; BAMBOX_FILAMENT_TYPE=PLA\n; BAMBOX_FILAMENT_TYPE=PETG-CF\n; BAMBOX_END\n"
        h = parse_bambox_headers(gcode)
        assert h["FILAMENT_TYPE"] == "PLA,PETG-CF"

    def test_multi_slot_headers(self) -> None:
        """Simulates CuraEngine output with per-extruder headers."""
        gcode = (
            "; BAMBOX_PRINTER=p1s\n"
            "; BAMBOX_EXTRUDERS=4\n"
            "; BAMBOX_ASSEMBLE=true\n"
            "G28\n"
            ";TYPE:CUSTOM\n"
            "; BAMBOX_FILAMENT_SLOT=0\n"
            "; BAMBOX_FILAMENT_TYPE=PLA\n"
            "T0\n"
            "G1 X10 Y10 E1 F600\n"
        )
        h = parse_bambox_headers(gcode)
        assert h["PRINTER"] == "p1s"
        assert h["EXTRUDERS"] == "4"
        assert h["FILAMENT_SLOT"] == "0"
        assert h["FILAMENT_TYPE"] == "PLA"

    def test_no_bambox_headers(self) -> None:
        gcode = "G28\nG1 Z0.2 F1200\n"
        h = parse_bambox_headers(gcode)
        assert h == {}

    def test_mixed_with_regular_comments(self) -> None:
        gcode = (
            "; generated by CuraEngine\n"
            ";FLAVOR:Marlin\n"
            "; BAMBOX_PRINTER=p1s\n"
            ";TIME:1234\n"
            "; BAMBOX_END\n"
        )
        h = parse_bambox_headers(gcode)
        assert h == {"PRINTER": "p1s"}
